# Generated by Django 3.2.13 on 2023-04-04 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
